language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
install: mvn dependency:resolve
script: mvn -B -P ci,jsSkip clean test
